changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Chores
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
